# @package _group_
train:
  batch_size: 128
  shuffle: True
  num_workers: 8
val:
  batch_size: 256
  shuffle: False
  num_workers: 8
test:
  # batch_size: 
  batch_size: 100
  shuffle: False
  num_workers: 4